In [1]:
import geopandas as gpd
import os

In [2]:
states = gpd.read_file(r"D:\Downloads\Administrative Boundary Database\STATE_BOUNDARY.shp")
grid = gpd.read_file(r"D:\CS\GitHub\Nuclear-Site-Selection\grid_points_within_states.shp")
coastline = gpd.read_file(r"D:\CS\GitHub\Nuclear-Site-Selection\coastline_gridpoints.shp")

In [3]:
coastline

,index_righ,STATE,State_LGD,Shape_Leng,Shape_Area,geometry
0,1,GUJARAT,24,5.255585e+06,1.768007e+11,POINT (2818972.400 4004537.862)
1,1,GUJARAT,24,5.255585e+06,1.768007e+11,POINT (2818972.400 4005537.862)
2,1,GUJARAT,24,5.255585e+06,1.768007e+11,POINT (2818972.400 4007537.862)
3,1,GUJARAT,24,5.255585e+06,1.768007e+11,POINT (2818972.400 4008537.862)
4,1,GUJARAT,24,5.255585e+06,1.768007e+11,POINT (2818972.400 4009537.862)
...,...,...,...,...,...,...
88404,757,ANDAMAN & NICOBAR,35,5.824763e+06,7.837276e+09,POINT (5572972.400 2201537.862)
88405,757,ANDAMAN & NICOBAR,35,5.824763e+06,7.837276e+09,POINT (5572972.400 2205537.862)
88406,757,ANDAMAN & NICOBAR,35,5.824763e+06,7.837276e+09,POINT (5572972.400 2206537.862)
88407,757,ANDAMAN & NICOBAR,35,5.824763e+06,7.837276e+09,POINT (5572972.400 2207537.862)
88408,757,ANDAMAN & NICOBAR,35,5.824763e+06,7.837276e+09,POINT (5573972.400 2201537.862)

In [7]:
column = 'STATE'
old = '>'
new = 'A'

In [8]:
grid[column] = grid[column].str.replace(old,new) 
grid['STATE'] = grid['STATE'].str.replace("|","I")

In [9]:
grid

,STATE,State_LGD,Shape_Leng,Shape_Area,geometry
0,GUJARAT,24,5.255585e+06,1.768007e+11,POINT (2848625.109 3997497.499)
1,GUJARAT,24,5.255585e+06,1.768007e+11,POINT (2849625.109 3994497.499)
2,GUJARAT,24,5.255585e+06,1.768007e+11,POINT (2849625.109 3995497.499)
3,GUJARAT,24,5.255585e+06,1.768007e+11,POINT (2849625.109 3996497.499)
4,GUJARAT,24,5.255585e+06,1.768007e+11,POINT (2849625.109 3997497.499)
...,...,...,...,...,...
872410,MANIPUR,14,9.084821e+05,2.148742e+10,POINT (5408625.109 4164497.499)
872411,MANIPUR,14,9.084821e+05,2.148742e+10,POINT (5409625.109 4158497.499)
872412,MANIPUR,14,9.084821e+05,2.148742e+10,POINT (5409625.109 4159497.499)
872413,MANIPUR,14,9.084821e+05,2.148742e+10,POINT (5409625.109 4160497.499)
872414,MANIPUR,14,9.084821e+05,2.148742e+10,POINT (5409625.109 4161497.499)

In [13]:

base_directory = r"D:\CS\GitHub\Nuclear-Site-Selection\state_wise_grid_points"
def create_directory(state_name):
    
    safe_state_name = state_name.replace(' ','_').replace('/','_')
    folder_path = os.path.join(base_directory,safe_state_name)

    if not os.path.exists(folder_path):
        os.makedirs(folder_path)
        print(f"Created folder: {folder_path}")
    else:
        print(f"Folder already exists: {folder_path}")